### ISSUE TITLE
Re-architect container image scheme

### ISSUE THREAD

**Issue by dboreham** [bozemanpass/stack#4]
The current scheme for container image tagging, discovery and so on is not able to meet the new goals for stack internal consistency, build optimization and so on.

Suggested changes/improvements:

 * Change image tag in compose files from e.g. `image: bpi/gitea:local` to `image: bpi/gitea:stack`
 * Assumption that the deployed image tag is always deployment-specific, e.g. `bpi/gitea:deploy-xxxxxxx`
 * Remove non-deployment deploy features, e.g. `stack deploy up`.
 * Repo-centric container image discovery/build (see below).

## Repo-centric container image scheme

In the stack definition file, container definitions are in terms of a repo-ref/path (old scheme of a bare name supported for backwards compatibility at least initially). Stack file would look like:

```
containers:
  - bozemanpass/gitea
    ref: github.com/bozemanpass/gitea-container@main
    path: <optional>
  - bozemanpass/act-runner
    ref: github.com/bozemanpass/act-runner-container@main
    path: <optional>
```

(The `path:` element could be removed if the relevant files can be found just from the container name)

The xxx-container repos contain sufficient information to allow the target image to be either fetched or built, replacing the contents of `/container-build`, via a descriptor file something like:

```
containers:
  - bozemanpass/gitea
    ref: github.com/telackey/gitea@telackey/sort
    build: ./build.sh
```

Target container image is found by either:

 1. Getting the git commit sha for the target repo/ref (e.g. `github.com/bozemanpass/gitea-container@main`) then looking in the associated container image registry (`https://github.com/bozemanpass/gitea-container/pkgs/container/gitea`) for an image with tagged with that sha. Or:
 2. Building the image locally using files fetched from the repo, then tagging it similarly.

There can be "stack-enabled" projects that provide enough information in their core repo to allow the xxx-container repo to be omitted.

### Lock File

The tool writes a lock file specifying the image tags built/fetched for the target stack. This allows reproduction of the stack subsequently (not really since the "world" can change, but at least better than nothing).

(Work in progress)
